# Cf. https://github.com/apache/arrow/blob/master/appveyor.yml

skip_commits:
  files:
    .github/*
    linux/*
    README.md
    .gitignore

environment:
  global:
    TEST_R_WITH_ARROW: TRUE
    RWINLIB_LOCAL: '%APPVEYOR_BUILD_FOLDER%\libarrow.zip'
    _R_CHECK_TESTS_NLINES_: 0
    BINTRAY_APIKEY:
      secure: bt7FQqKZhZA93YURBaizwiNGU45nl7kUqAPeN/bIiArLypKkbbPs4lGeWjXEx7qF
  matrix:
    # Can't go older than R 3.3 because we need Rtools 3.5
    - R_VERSION: 3.3.3
      PKGTYPE: both
    - R_VERSION: 3.4.4
    - R_VERSION: 3.5.3
    - R_VERSION: release
    - R_VERSION: devel
      # CRAN is broken since the internal version bumped to 4.0 but the repo
      # has 3.7, so dependencies have to be built from source (no binary for 4.0)
      PKGTYPE: both
cache:
  - c:\RLibrary
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - git clone --depth=1 https://github.com/apache/arrow.git
  # The build scripts in apache/arrow assume that they're in a specific location
  # so we need to copy certain files up a level
  - mkdir ci
  - copy arrow\ci\PKGBUILD ci\
  - copy arrow\ci\appveyor-build-r.sh ci\
  - copy arrow\ci\windows-pkg-arrow-for-r.sh ci\
  - xcopy /S /I arrow\cpp cpp
  - xcopy /S /I arrow\format format
  - xcopy /S /I arrow\r r
  - cd r
  - ps: Bootstrap
  - travis-tool.sh install_deps

before_build:
  # Add today's date as the patch version for the R package
  - cmd: bash ../up-date-description.sh

build_script:
  # Build the C++ library
  - cd %APPVEYOR_BUILD_FOLDER%
  - rmdir /s /Q C:\OpenSSL-Win32 C:\OpenSSL-Win64
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/appveyor-build-r.sh"
  - pushd r

test_script:
  # This builds the binary package in the process of running R CMD check
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

on_success:
  - cmd: bash ../bintray-upload.sh

artifacts:
  - path: 'r\*.Rcheck\**\*.log'
    name: Logs

  - path: 'r\*.Rcheck\**\*.out'
    name: Logs

  - path: 'r\*.Rcheck\**\*.fail'
    name: Logs

  - path: 'r\*.Rcheck\**\*.Rout'
    name: Logs

  - path: 'r\*_*.tar.gz'
    name: Source

  - path: 'r\*_*.zip'
    name: Binary
