name: Binary Windows R packages

on:
  schedule:
    - cron: |
        0 5 * * *
  push:
    paths:
      - ".github/workflows/build-binary-packages.yml"
      - s3-upload.py
      - build-binary-and-upload.R

jobs:
  package:
    name: ${{ matrix.platform }} ${{ matrix.r_version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest
          # This is newer than what CRAN builds on, but Travis is no longer an option for us, so...
          - macos-latest
        r_version:
          # - "3.5"
          - "3.6"
          - "4.0"
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v2
      - name: Set up Python (for S3 upload)
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Boto
        run: |
          python -m pip install boto3
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r_version }}
          Ncpus: 2
      - name: Build and upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: Rscript {0}
        run: source("build-binary-and-upload.R")
