name: Daily pkgdown site

on:
  schedule:
    - cron: |
        0 22 * * *
  push:
    paths:
      - '.github/workflows/pkgdown.yml'

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clone apache/arrow
        shell: bash
        run: |
          git clone https://github.com/apache/arrow
      - name: Checkout arrow at date and update R package version
        shell: bash
        run: |
          cd arrow
          git checkout `git rev-list -n 1 --before="00:00" master`
          cd r
          cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
          export DATE=$(date -d yesterday +%Y%m%d)
          source ../../up-date-description.sh
      - name: Set up gh-pages branch to push to
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "$(git log -1 --pretty=format:%an)"
          git config --global user.email "$(git log -1 --pretty=format:%ae)"
          cd arrow/r
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/ursa-labs/arrow-r-nightly.git docs
          cd docs
          TARGET_BRANCH=gh-pages
          if ! git checkout gh-pages; then
            git checkout --orphan gh-pages
            rm -rf *
            # So that pkgdown recognizes that it can write here
            touch pkgdown.yml
          fi
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies and package
        run: Rscript linux/install-with-pkgdown.R
      - name: Build and deploy site
        run: |
          cd arrow/r
          Rscript -e "pkgdown::build_site(install = FALSE)"
          cd docs
          if [ "$(git status --porcelain)" != "" ]; then
            # There are changes to the built site
            export DATE=$(date -d yesterday +%Y%m%d)
            git add --all
            git commit -m "Updating pkgdown site (${DATE})"
            git push origin gh-pages
          else
            echo "No changes to the built site"
          fi
