name: Test binary installation

on:
  schedule:
    - cron: |
        0 23 * * *
  push:
    paths:
      - '.github/workflows/test-binary.yml'
      - 'linux/install-arrow.R'
      - 'linux/distro-map.csv'
  # On tag too?

jobs:
  binary:
    name: Binary packages
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - "rhub/ubuntu-gcc-release" # ubuntu-16.04
          - "rstudio/r-base:3.6-bionic"
          - "rstudio/r-base:3.6-centos7"
          - "rstudio/r-base:3.6-centos8"
          - "rocker/r-ver:3.6.3" # for debian:buster (10)
          - "rocker/r-ver" # ubuntu-20.04
          - "rhub/fedora-clang-devel" # tests distro-map.csv, mapped to centos-8
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Install system requirements
        run: source linux/install-system-requirements.sh
      - name: Install arrow from binatray
        run: PATH=/opt/R-devel/bin:$PATH Rscript linux/install-arrow.R
